# Generated by Django 6.0.6 on 2026-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_city'),
        ('users', '0002_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='services.service'),
        ),
    ]
