# Generated by Django 6.0.6 on 2026-07-30 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_image_url_service_instagram_service_website_and_more'),
        ('users', '0003_customuser_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='unique_recent_service_per_user')],
            },
        ),
    ]
