# Generated by Django 6.0.6 on 2026-06-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
    ]
