# Generated by Django 6.0.6 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
