# Generated by Django 6.0.6 on 2026-07-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('services', '0004_service_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='cities.city'),
        ),
    ]
