# Generated by Django 6.0.6 on 2026-07-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('box', models.ForeignKey(blank=True, help_text='Оставьте пустым, чтобы перерыв действовал на весь бизнес.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_breaks', to='services.box')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_breaks', to='services.service')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('is_working', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('box', models.ForeignKey(blank=True, help_text='Оставьте пустым для общего графика бизнеса.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='services.box')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='services.service')),
            ],
            options={
                'ordering': ['box_id', 'weekday'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('box__isnull', True)), fields=('service', 'weekday'), name='unique_service_weekly_schedule'), models.UniqueConstraint(condition=models.Q(('box__isnull', False)), fields=('box', 'weekday'), name='unique_box_weekly_schedule')],
            },
        ),
    ]
