# Generated by Django 6.0.6 on 2026-07-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_schedulebreak_weeklyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('boxes', models.ManyToManyField(blank=True, related_name='offerings', to='services.box')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='services.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('boxes', models.ManyToManyField(blank=True, related_name='employees', to='services.box')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='services.service')),
                ('offerings', models.ManyToManyField(blank=True, related_name='employees', to='services.serviceoffering')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='services.box')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='services.service')),
            ],
            options={
                'ordering': ['date', 'box_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('box__isnull', True)), fields=('service', 'date'), name='unique_service_schedule_exception'), models.UniqueConstraint(condition=models.Q(('box__isnull', False)), fields=('box', 'date'), name='unique_box_schedule_exception')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='unique_offering_name_per_service'),
        ),
    ]
