# Generated by Django 6.0.6 on 2026-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slot_unit',
            field=models.CharField(default='Бокс', max_length=50),
        ),
    ]
