# Generated by Django 6.0.6 on 2026-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_slot_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на картинку с Unsplash или другого сайта'),
        ),
    ]
