# Generated by Django 6.0.6 on 2026-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_backfill_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
