# Generated by Django 6.0.6 on 2026-07-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_no_show_marked_at_booking_owner_note'),
        ('services', '0007_service_image_url_service_instagram_service_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_confirmation',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('confirmed', 'Клиент придёт'), ('declined', 'Клиент не сможет прийти')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_note', models.TextField(blank=True)),
                ('preferences', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_client_cards', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cards', to='services.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'client'), name='unique_client_card_per_service')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ожидает'), ('booked', 'Записался'), ('cancelled', 'Отменено')], default='active', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'service'), name='unique_active_waitlist_entry')],
            },
        ),
    ]
